### PR TITLE
add properties to containers

### PR DESCRIPTION
**Pull request by clement26695**
-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/generator-jhipster/pull_requests) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by clement26695** [comment]
ping @pascalgrimaud

**Comment by pascalgrimaud** [comment]
@clement26695 : does it work when you start with `app.yml`?

**Comment by clement26695** [comment]
didn't test, haha ! Will do this afternoon :)

**Comment by clement26695** [comment]
Just tested locally and everything seems to work as expected. 

I just moved the `depends_on` to the app.yml but I guess it could be totally removed (it works locally without it). 

I am also not sure if all the values I added to the app.yml are necessary, as I don't know exactly how the Docker image of the app is built (I tried without them and everything looks fine)

**Comment by pascalgrimaud** [comment]
@clement26695 : let's remove depends_on if it's not necessary

Then, about properties, although it's the same than in application.yml, I like to have it, because these properties are important and will probably be overwritten in real production. But it's just my point of view, we can keep or remove them, it will be the same result

**Comment by clement26695** [comment]
Just updated the PR with your remarks @pascalgrimaud. Let's keep the values since you think it is useful :)

**Comment by pascalgrimaud** [comment]
I manually merge this, using my local branch and push directly to the PR

**Pull request merged**
